### ISSUE TITLE
anyone got this issue???

### ISSUE THREAD

**Issue by DeonLee85** [Yggdrasils/Metamon#7]

**Comment by DeonLee85** [comment]
Traceback (most recent call last):
  File "C:\Users\Downloads\Metamon-main (1)\Metamon-main\metamon.py", line 251, in <module>
    my_metamon.addAttr(lvrange=[1,60], scarange=[305,400], attrtype="luck")
  File "C:\Users\Downloads\Metamon-main (1)\Metamon-main\metamon.py", line 180, in addAttr
    self.addAttr_data["attrType"] = attribute[luck]
NameError: name 'luck' is not defined

**Comment by rnoh96** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

Zaskoda, @kchulj, @crrrrrw, @chedlibelfguira2018, @baumere, @a13z, @kimhaka210, @SBefaro, @jie1789, @victorsh, @thaothuy2535557, @elliereid, @melvin0008, @Durev, @emmaodia, @ricaurte, @npanium, @filmblackeye, @GrandGarcon, @Lobster070
